[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
picassol = "p1Z5CJa9U1e3XU9Uq9zhCQArD19MidRfBdMHPowtoim"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/devenv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
